// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIPytks_k82wzLgbvm4IVZDkrFwSSvSpg',
    appId: '1:213413638616:web:2215ca5e9098741b4502ad',
    messagingSenderId: '213413638616',
    projectId: 'ky-trade-mark',
    authDomain: 'ky-trade-mark.firebaseapp.com',
    storageBucket: 'ky-trade-mark.firebasestorage.app',
    measurementId: 'G-GJ2KKQ7YK2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuI5SS9ZNa5uVPCDQCabDSfd0LWRfPc2U',
    appId: '1:213413638616:ios:2ae5e15b737f99e34502ad',
    messagingSenderId: '213413638616',
    projectId: 'ky-trade-mark',
    storageBucket: 'ky-trade-mark.firebasestorage.app',
    androidClientId: '213413638616-tio96658t5606v569iski4683pkmeet6.apps.googleusercontent.com',
    iosBundleId: 'com.dokkan.KyTradeMarksDelivery',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkryo3H-OaROy8kN4R3qJriRzKFjK4Uw',
    appId: '1:213413638616:android:8a96412e766f41ba4502ad',
    messagingSenderId: '213413638616',
    projectId: 'ky-trade-mark',
    storageBucket: 'ky-trade-mark.firebasestorage.app',
  );

}